## Lab 3: pandas

#### Introduction

We will examine a dataset containing characteristics of lego sets manufactured between 1961 and 2019 from the BRICKSET website. Variables in the dataset are described below.

| VARIABLE             |      DESCRIPTION             |
|:----------|:-------------|
| ID |  set id |
| Name |    name of set   |
| Themegroup | themegroup of set |
| Theme |  theme of set |
| Subtheme |    subtheme of set   |
| Year | year released |
| Pieces |  number of pieces |
| Minifig |    number of minifigs   |
| Package | type of packaging |
| Retail_Price |  recommended retail pri



Load pandas to read in the data and save it as dataframe named lego.

In [2]:
import pandas as pd

lego = pd.read_csv('lego.csv')

#### Question 1:
Some sets have missing information for retail_price or pieces or both. This could be because the sets are free (giveaways), they aren’t traditional lego sets (comic books, etc) or just because the information is missing. Filter the lego dataset based on the specifications below and save the result as lego. Hence, you will overwrite the original lego object. In addition, describe the implications of removing these sets.

Your new lego (data frame) should have:

• no missing pieces

• only contain sets with a nonzero number of pieces

• no missing retail_price

• only contain sets with a nonzero retail_price

• no missing year

- Print out the shape of the dataframe after cleaning the dataset.
-

In [4]:
# Write your answer here

import pandas as pd

lego = pd.read_csv('lego.csv')
lego.describe()
lego.loc[lego.retail_price == 0, : ].head(7)

print(lego.shape)
lego2 = lego.dropna()
print(lego2.shape)
lego2 = lego2.loc[lego2.retail_price > 0, : ]
print(lego2.shape)

(12214, 10)
(4360, 10)
(4277, 10)

In [6]:
lego2.sample(7)
lego2.describe()

              year       pieces     minifigs  retail_price
count  4277.000000  4277.000000  4277.000000   4277.000000
mean   2008.243395   251.114099     2.110592     29.231814
std       9.602551   433.553512     2.479037     41.633822
min    1961.000000     1.000000     0.000000      0.500000
25%    2002.000000    38.000000     0.000000      4.990000
50%    2012.000000   109.000000     1.000000     14.990000
75%    2015.000000   305.000000     3.000000     38.500000
max    2019.000000  7541.000000    28.000000    799.990000

#### Question 2:	
Arrange the dataset in descending order of retail_price and print the first three rows. Report in words the names of the three most expensive lego sets, their prices, and how many pieces each has.

In [8]:
# Write your answer here
lego2.sort_values(by = 'retail_price', ascending = False).head(3)

,id,name,themegroup,theme,subtheme,year,pieces,minifigs,package,retail_price
1434,75192-1,Millennium Falcon,Licensed,Star Wars,Ultimate Collector Series,2017.0,7541.0,8,Box,799.99
5944,10179-1,Ultimate Collector's Millennium Falcon,Licensed,Star Wars,Ultimate Collector Series,2007.0,5197.0,5,Box,499.99
2065,75159-1,Death Star,Licensed,Star Wars,Ultimate Collector Series,2016.0,4016.0,27,Box,499.99

#### Question 3:

It appears that the most expensive sets generally have more pieces. Create a new variable (column) price_per_piece, representing the price in dollars per piece for each of the sets. Save the result as lego2. Hence, you will overwrite the current lego object.

In [24]:
# Write your answer here
#Q3 Explanation
lego2.theme.unique()

array(['Creator Expert', 'Toy Story', 'Duplo', 'Architecture',
       'Minecraft', 'Ideas', 'City', 'BrickHeadz', 'Ninjago',
       'The Lego Movie 2: The Second Part', 'Star Wars',
       'Speed Champions', 'Jurassic World', 'Marvel Super Heroes',
       'DC Comics Super Heroes', 'Classic', 'Juniors', 'Wizarding World',
       'Creator', 'Miscellaneous', 'Seasonal', 'Promotional', 'Disney',
       'Unikitty', 'Friends', 'The LEGO Ninjago Movie',
       'Collectable Minifigures', 'Nexo Knights', 'The LEGO Batman Movie',
       'Pirates of the Caribbean', 'Dimensions', 'Mixels', 'Bionicle',
       'Legends of Chima', 'Education', 'Teenage Mutant Ninja Turtles',
       'The LEGO Movie', 'The Hobbit', 'The Lord of the Rings', 'Space',
       'Mindstorms', 'Games', 'Castle', 'Monster Fighters',
       'Bricks and More', 'Cars', 'Harry Potter', 'Racers',
       'Power Functions', 'Indiana Jones', 'Pirates', 'Factory',
       'Exo-Force', 'Trains', 'Sports', 'Town', 'World City',
       'Alpha Team', 'Spider-Man', 'Bulk Bricks', 'Explore',
       'Adventurers', 'Studios', 'Western', 'Technic', 'Basic',
       'Aquazone', 'Service Packs', 'Time Cruisers', 'Assorted', 'Books',
       'Samsonite', 'LEGOLAND'], dtype=object)

In [12]:
# Harry theme set
lego2.loc[lego2.theme == 'Harry Potter', : ].shape

(50, 10)

In [14]:
lego2.loc[lego2.theme == 'Harry Potter', : ].retail_price.mean

<bound method Series.mean of 4440    149.99
4561      4.99
4562      3.99
4608      4.99
4627     11.99
4628     34.99
4629     49.99
4977     10.99
4978     19.99
4979     39.99
4980     59.99
4981     79.99
4982    129.99
5998     89.99
6522     20.00
6523     30.00
6524     30.00
6525     49.99
6782    120.00
6889      8.00
6890     10.00
6891     20.00
6892     20.00
6893     30.00
6894     30.00
6895     50.00
6896     90.00
6897     40.00
7281     10.00
7282     20.00
7642     10.00
7643     30.00
7644     13.00
7645     20.00
7646     30.00
7647     50.00
7648     70.00
7649      7.00
7650     20.00
7651     10.00
7985      7.00
7986     10.00
7987     20.00
7988     20.00
7989     30.00
7990     30.00
7991     50.00
7992     90.00
7993     10.00
7994     10.00
Name: retail_price, dtype: float64>

In [16]:
lego2.loc[lego2.theme == 'Harry Potter', : ].sample(6)

,id,name,themegroup,theme,subtheme,year,pieces,minifigs,package,retail_price
7987,4704-1,The Room of the Winged Keys,Licensed,Harry Potter,Philosopher's Stone,2001.0,175.0,3,Box,20.00
6893,4754-1,Hagrid's Hut,Licensed,Harry Potter,Prisoner of Azkaban,2004.0,302.0,2,Box,30.00
7649,4731-1,Dobby's Release,Licensed,Harry Potter,Chamber of Secrets,2002.0,70.0,2,Box,7.00
7647,4729-1,Dumbledore's Office,Licensed,Harry Potter,Chamber of Secrets,2002.0,446.0,3,Box,50.00
4979,4738-1,Hagrid's Hut,Licensed,Harry Potter,General,2010.0,442.0,4,Box,39.99
4629,4867-1,Hogwarts,Licensed,Harry Potter,Deathly Hallows,2011.0,466.0,7,Box,49.99

In [18]:
lego2.loc[lego2.theme == 'Harry Potter', ['name', 'themegroup', 'theme', 'subtheme']].sample(6)

,name,themegroup,theme,subtheme
6897,Hogwarts Express,Licensed,Harry Potter,Prisoner of Azkaban
7281,Quality Quidditch Supplies,Licensed,Harry Potter,Chamber of Secrets
4608,Mini Hogwarts Express,Licensed,Harry Potter,Mini Building Set
6889,Draco's Encounter with Buckbeak,Licensed,Harry Potter,Prisoner of Azkaban
6896,Hogwarts Castle,Licensed,Harry Potter,Prisoner of Azkaban
7645,Aragog in the Dark Forest,Licensed,Harry Potter,Chamber of Secrets

In [20]:
lego2.sort_values(by = 'retail_price', ascending = False).tail(3)

,id,name,themegroup,theme,subtheme,year,pieces,minifigs,package,retail_price
12083,806-2,Cowboy & Pony,Vintage themes,Samsonite,Model Maker,1964.0,87.0,0,Blister pack,0.98
12091,520-4,2 X 2 Plate (Flat Roof Bricks with 4 Studs),Vintage themes,Samsonite,Supplemental,1961.0,40.0,0,Box,0.50
12106,215-3,2 X 8 Bricks,Vintage themes,Samsonite,Supplemental,1961.0,9.0,0,Box,0.50

In [22]:
#Q3 Real solution 
lego2['price_per_piece'] = lego2.retail_price / lego2.pieces
lego2.sample(6)

,id,name,themegroup,theme,subtheme,year,pieces,minifigs,package,retail_price,price_per_piece
4701,7065-1,Alien Mothership,Action/Adventure,Space,Alien Conquest,2011.0,416.0,2,Box,59.99,0.144207
1755,41563-1,Splasho,Licensed,Mixels,Series 8,2016.0,67.0,0,Foil pack,4.99,0.074478
912,10259-1,Winter Village Station,Model making,Creator Expert,Winter Village,2017.0,902.0,5,Box,79.99,0.088681
628,60174-1,Mountain Police Headquarters,Modern day,City,Mountain Police,2018.0,663.0,7,Box,89.99,0.135732
6909,4857-1,Doc Ock's Fusion Lab,Licensed,Spider-Man,Spider-Man 2,2004.0,237.0,4,Box,20.00,0.084388
7174,3535-1,Skateboard Street Park,Modern day,Sports,Gravity Games,2003.0,69.0,1,Box,10.00,0.144928

#### Question 4:	

Arrange the lego2 dataset in descending order of price_per_piece and return only the columns: name, themegroup, theme, pieces, price_per_piece, and the first five rows. What do you notice about these sets?

In [34]:
# Write your answer here

#Q4
#Way1: Common way, all same line

lego2.sort_values(by = 'price_per_piece' , ascending = False).loc[:, ['name', 'themegroup', 'theme', 'pieces', 'price_per_piece']].head(5)

,name,themegroup,theme,pieces,price_per_piece
5551,Rechargeable Battery Box,Technical,Power Functions,1.0,49.990
5553,Transformer 10V DC,Technical,Power Functions,1.0,29.990
5616,Collectable Display Set 2,Licensed,Star Wars,2.0,24.995
8694,Temperature Sensor,Technical,Mindstorms,1.0,24.000
7540,Robotics Invention System Upgrade Kit,Technical,Mindstorms,1.0,20.000

In [32]:
#Way2: Dividing the steps
sorted_lego = lego2.sort_values(by = 'price_per_piece' , ascending = False)
sorted_lego = sorted_lego.loc[:, ['name', 'themegroup', 'theme', 'pieces', 'price_per_piece']]
sorted_lego.head(5)

,name,themegroup,theme,pieces,price_per_piece
5551,Rechargeable Battery Box,Technical,Power Functions,1.0,49.990
5553,Transformer 10V DC,Technical,Power Functions,1.0,29.990
5616,Collectable Display Set 2,Licensed,Star Wars,2.0,24.995
8694,Temperature Sensor,Technical,Mindstorms,1.0,24.000
7540,Robotics Invention System Upgrade Kit,Technical,Mindstorms,1.0,20.000

#### Question 5:

What is the mean price_per_piece for the top 40 'Toy Story' sets in terms of price_per_piece?

In [36]:
# Write your answer here

lego2.loc[ lego.theme == 'Stars Wars', :].retail_price.mean()

nan

In [38]:
lego2.loc[ lego.theme == 'Toy Story', :].retail_price.mean()

36.32333333333334

In [40]:
lego2.loc[ lego.theme == 'Minecraft', :].retail_price.mean()

51.101111111111095

In [44]:
# Q5 Solution:
sorted_lego.loc[ sorted_lego.theme == 'Toy Story', :].head(40).price_per_piece.mean()

0.16089862892544177

In [46]:
sorted_lego.loc[ sorted_lego.theme == 'Stars Wars', :].head(40).price_per_piece.mean()

nan

#### Question 6:

What are the unique themes in the lego dataset?

In [48]:
# Write your answer here
#Q6
lego2.theme.unique()

array(['Creator Expert', 'Toy Story', 'Duplo', 'Architecture',
       'Minecraft', 'Ideas', 'City', 'BrickHeadz', 'Ninjago',
       'The Lego Movie 2: The Second Part', 'Star Wars',
       'Speed Champions', 'Jurassic World', 'Marvel Super Heroes',
       'DC Comics Super Heroes', 'Classic', 'Juniors', 'Wizarding World',
       'Creator', 'Miscellaneous', 'Seasonal', 'Promotional', 'Disney',
       'Unikitty', 'Friends', 'The LEGO Ninjago Movie',
       'Collectable Minifigures', 'Nexo Knights', 'The LEGO Batman Movie',
       'Pirates of the Caribbean', 'Dimensions', 'Mixels', 'Bionicle',
       'Legends of Chima', 'Education', 'Teenage Mutant Ninja Turtles',
       'The LEGO Movie', 'The Hobbit', 'The Lord of the Rings', 'Space',
       'Mindstorms', 'Games', 'Castle', 'Monster Fighters',
       'Bricks and More', 'Cars', 'Harry Potter', 'Racers',
       'Power Functions', 'Indiana Jones', 'Pirates', 'Factory',
       'Exo-Force', 'Trains', 'Sports', 'Town', 'World City',
       'Alpha Team', 'Spider-Man', 'Bulk Bricks', 'Explore',
       'Adventurers', 'Studios', 'Western', 'Technic', 'Basic',
       'Aquazone', 'Service Packs', 'Time Cruisers', 'Assorted', 'Books',
       'Samsonite', 'LEGOLAND'], dtype=object)

In [50]:
#From the filtered
lego2.theme.value_counts()

#For each theme how many sets in the sets??

# From the not filtered
lego.theme.unique()

array(['Promotional', 'Creator Expert', 'Toy Story', 'Duplo', 'Classic',
       'Education', 'Architecture', 'Minecraft', 'Ideas',
       'The Lego Movie 2: The Second Part', 'City', 'Friends',
       'Marvel Super Heroes', 'Ninjago', 'Creator', 'Seasonal', 'Xtra',
       'BrickHeadz', 'Miscellaneous', 'Disney', 'Technic', 'Gear',
       'Collectable Minifigures', 'Star Wars', 'Speed Champions',
       'Jurassic World', 'Overwatch', 'DC Comics Super Heroes', 'FORMA',
       'Powered Up', 'Juniors', 'Unikitty', 'Wizarding World',
       'The LEGO Batman Movie', 'Elves', 'The Powerpuff Girls', 'Explore',
       'The LEGO Ninjago Movie', 'Nexo Knights', 'Harry Potter', 'Boost',
       'DC Super Hero Girls', 'CITY', 'Pirates of the Caribbean',
       'Dimensions', 'Books', 'Scooby-Doo', 'Mixels', 'Mindstorms',
       'Bionicle', 'Castle', 'The Angry Birds Movie', 'Ghostbusters', nan,
       'Space', 'Legends of Chima', 'Pirates', 'Serious Play',
       'Ultra Agents', 'The LEGO Movie', 'The Simpsons',
       'Bricks and More', 'Fusion', 'Teenage Mutant Ninja Turtles',
       'HERO Factory', 'The Hobbit', 'The Lord of the Rings',
       'Master Builder Academy', 'The Lone Ranger', 'Games',
       'Power Functions', 'Monster Fighters', 'Life of George', 'Racers',
       'SpongeBob SquarePants', 'Make and Create', 'Dino', 'Cars',
       "Pharaoh's Quest", 'Atlantis', 'Prince of Persia', 'Primo',
       'World Racers', 'Power Miners', 'Ben 10: Alien Force',
       'Indiana Jones', 'Agents', 'Factory', 'Belville', 'Batman',
       'Exo-Force', 'Sports', 'Aqua Raiders', 'Trains',
       'Avatar The Last Airbender', 'World City', 'Quatro', 'Vikings',
       'Clikits', 'Bulk Bricks', 'Spider-Man', 'Dino 2010', 'Dino Attack',
       'Model Team', 'Town', 'Alpha Team', '4 Juniors', 'Hobby Set',
       'Discovery', 'Adventurers', 'Island Xtreme Stunts', 'Basic',
       'Studios', 'Jack Stone', 'Spybotics', 'Galidor', 'Western',
       'Dacta', 'Action Wheelers', 'Scala', 'Dinosaurs', 'Rock Raiders',
       'Mickey Mouse', 'Service Packs', 'Aquazone', 'Znap', 'Freestyle',
       'Time Cruisers', 'Boats', 'Assorted', 'Fabuland',
       'Universal Building Set', 'Homemaker', 'Samsonite', 'PreSchool',
       'LEGOLAND', 'Building Set with People', 'Minitalia', 'System',
       'Legoland'], dtype=object)